apiVersion: v1
kind: Namespace
metadata:
  name: user-template
  labels:
    platform: event-driven
    type: user-namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-quota
  namespace: user-template
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: user-limits
  namespace: user-template
spec:
  limits:
  - max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sa
  namespace: user-template
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-role
  namespace: user-template
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - services
  - endpoints
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ["apps"]
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ["camel.apache.org"]
  resources:
  - integrations
  - integrations/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-rolebinding
  namespace: user-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-role
subjects:
- kind: ServiceAccount
  name: user-sa
  namespace: user-template
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kafka-rabbitmq
  namespace: user-template
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          platform: event-driven
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kafka
    ports:
    - protocol: TCP
      port: 9092
    - protocol: TCP
      port: 9093
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: rabbitmq
    ports:
    - protocol: TCP
      port: 5672
    - protocol: TCP
      port: 15672
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector: {}
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: camel-k
  namespace: user-template
spec:
  build:
    registry:
      organization: camel-k
    maven:
      settings:
        configMapKeyRef:
          key: settings.xml
          name: maven-settings
    timeout: 10m
  cluster: Kubernetes
  profile: Kubernetes
  traits:
    container:
      configuration:
        requestCPU: "200m"
        requestMemory: "256Mi"
        limitCPU: "500m"
        limitMemory: "512Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
  namespace: user-template
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                  https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <localRepository>/tmp/artifacts/m2</localRepository>
      <mirrors>
        <mirror>
          <id>central-mirror</id>
          <mirrorOf>central</mirrorOf>
          <url>https://repo1.maven.org/maven2</url>
        </mirror>
      </mirrors>
    </settings>
