---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: backstage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
  # Read access to common resources
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - limitranges
      - resourcequotas
      - namespaces
    verbs:
      - get
      - list
      - watch
  
  # Read access to apps
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
  
  # Read access to batch jobs
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  
  # Read access to networking
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  
  # Read access to Kafka (Strimzi)
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkaconnects
      - kafkatopics
      - kafkausers
    verbs:
      - get
      - list
      - watch
  
  # Read access to RabbitMQ
  - apiGroups:
      - rabbitmq.com
    resources:
      - rabbitmqclusters
    verbs:
      - get
      - list
      - watch
  
  # Read access to Camel K
  - apiGroups:
      - camel.apache.org
    resources:
      - integrations
      - integrationplatforms
    verbs:
      - get
      - list
      - watch
  
  # Read access to metrics
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-read-only
subjects:
  - kind: ServiceAccount
    name: backstage
    namespace: backstage
