apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-k-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-k-operator
  template:
    metadata:
      labels:
        app: camel-k-operator
        name: camel-k-operator
    spec:
      serviceAccountName: camel-k-operator
      containers:
      - name: camel-k-operator
        image: apache/camel-k:2.5.0
        imagePullPolicy: IfNotPresent
        command:
        - kamel
        - operator
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: OPERATOR_NAME
          value: camel-k
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5