---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camel-k-operator
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camel-k-operator
rules:
  - apiGroups: [camel.apache.org]
    resources: ['*']
    verbs: ['*']
  - apiGroups: [""]
    resources: [pods, services, endpoints, persistentvolumeclaims, configmaps, secrets, serviceaccounts]
    verbs: ['*']
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, rolebindings]
    verbs: ['*']
  - apiGroups: [apps]
    resources: [deployments, replicasets, statefulsets]
    verbs: ['*']
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: camel-k-operator
subjects:
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: operators
roleRef:
  kind: ClusterRole
  name: camel-k-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-k-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-k-operator
  template:
    metadata:
      labels:
        app: camel-k-operator
    spec:
      serviceAccountName: camel-k-operator
      containers:
        - name: camel-k-operator
          image: apache/camel-k:2.5.0
          command:
            - kamel
            - operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: camel-k
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10