apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-cluster-operator
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-cluster-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - persistentvolumeclaims
  - pods
  - pods/exec
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  - rabbitmqclusters/status
  - rabbitmqclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rabbitmq-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbitmq-cluster-operator
subjects:
- kind: ServiceAccount
  name: rabbitmq-cluster-operator
  namespace: operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-cluster-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-cluster-operator
    spec:
      serviceAccountName: rabbitmq-cluster-operator
      containers:
      - name: operator
        image: rabbitmqoperator/cluster-operator:2.10.0
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqclusters.rabbitmq.com
spec:
  group: rabbitmq.com
  names:
    kind: RabbitmqCluster
    listKind: RabbitmqClusterList
    plural: rabbitmqclusters
    singular: rabbitmqcluster
    shortNames:
    - rmq
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 0
              image:
                type: string
              imagePullSecrets:
                type: array
                items:
                  type: object
              service:
                type: object
              persistence:
                type: object
              resources:
                type: object
              affinity:
                type: object
              tolerations:
                type: array
              override:
                type: object
              rabbitmq:
                type: object
              tls:
                type: object
              skipPostDeploySteps:
                type: boolean
              terminationGracePeriodSeconds:
                type: integer
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: AllReplicasReady
      type: string
      jsonPath: .status.conditions[?(@.type=="AllReplicasReady")].status
    - name: ReconcileSuccess
      type: string
      jsonPath: .status.conditions[?(@.type=="ReconcileSuccess")].status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
