---
# CRD MUST be created first - this is what RabbitMQ operator needs on startup
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqclusters.rabbitmq.com
spec:
  group: rabbitmq.com
  scope: Namespaced
  names:
    kind: RabbitmqCluster
    listKind: RabbitmqClusterList
    singular: rabbitmqcluster
    plural: rabbitmqclusters
    shortNames:
      - rmq
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-cluster-operator
rules:
  - apiGroups: [""]
    resources: [configmaps, secrets, services, persistentvolumeclaims, pods, events]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [statefulsets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [rabbitmq.com]
    resources: [rabbitmqclusters, rabbitmqclusters/status, rabbitmqclusters/finalizers]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rabbitmq-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbitmq-cluster-operator
subjects:
  - kind: ServiceAccount
    name: rabbitmq-cluster-operator
    namespace: rabbitmq-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-cluster-operator
    spec:
      serviceAccountName: rabbitmq-cluster-operator
      containers:
        - name: operator
          image: rabbitmqoperator/cluster-operator:2.10.0
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi