---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-cluster-operator
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-global
rules:
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [clusterrolebindings]
    verbs: [get, create, delete, patch, update, watch]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-namespaced
rules:
  - apiGroups: [""]
    resources: [serviceaccounts, configmaps, services, secrets, persistentvolumeclaims, pods]
    verbs: [get, create, delete, patch, update, list, watch]
  - apiGroups: [kafka.strimzi.io]
    resources: ['*']
    verbs: ['*']
  - apiGroups: [apps]
    resources: [deployments, statefulsets]
    verbs: [get, create, delete, patch, update, list, watch]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [rolebindings]
    verbs: [get, create, delete, patch, update]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: [get, create, delete, patch, update, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies, ingresses]
    verbs: [get, create, delete, patch, update, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: operators
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator-global
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator
  namespace: operators
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: operators
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: operators
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator:0.43.0
          env:
            - name: STRIMZI_NAMESPACE
              value: kafka
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.7.0=quay.io/strimzi/kafka:0.43.0-kafka-3.7.0
                3.7.1=quay.io/strimzi/kafka:0.43.0-kafka-3.7.1
                3.8.0=quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.7.0=quay.io/strimzi/kafka:0.43.0-kafka-3.7.0
                3.7.1=quay.io/strimzi/kafka:0.43.0-kafka-3.7.1
                3.8.0=quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                3.7.0=quay.io/strimzi/kafka:0.43.0-kafka-3.7.0
                3.7.1=quay.io/strimzi/kafka:0.43.0-kafka-3.7.1
                3.8.0=quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                3.7.0=quay.io/strimzi/kafka:0.43.0-kafka-3.7.0
                3.7.1=quay.io/strimzi/kafka:0.43.0-kafka-3.7.1
                3.8.0=quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator:0.43.0
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator:0.43.0
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator:0.43.0
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge:0.29.0
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30