apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camelk
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/<your-repo>.git  # CHANGE THIS
    targetRevision: main
    path: base/camelk
  destination:
    server: https://kubernetes.default.svc
    namespace: camelk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  syncWaves:
    - wave: 1
